### ISSUE TITLE
Support default environment variables for client instantiation

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns-java#65]
Provide a way to load a client from environment variables using no arguments in `VinylDNSClientImpl`. The environment variable naming should maintain consistency with our other clients:
- `VINYLDNS_API_URL`
- `VINYLDNS_ACCESS_KEY_ID`
- `VINYLDNS_SECRET_ACCESS_KEY`

Note: A combination of `EnvironmentVariableCredentialsProvider` for AWS credentials and `System.env` can be used to implement this.

**Comment by mdb** [comment]
@mitruly Am I correct in thinking this can now be closed, as it's been addressed by PR #76 ?

**Comment by mitruly** [comment]
Yes, you are correct @mdb. Closing this issue.
