### ISSUE TITLE
Add RecordSet search support

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns-java#81]
### Description
The VinylDNS API has been updated to include a new [global recordset search endpoint](https://www.vinyldns.io/api/list-recordsets-global.html) at `/recordsets`. This client should be updated to support this new endpoint.

**Comment by djordan17** [comment]
Hi mitruly, I worked on the issue, but I don't know if I did the right thing.
I created a **fork** and made PR **https://github.com/vinyldns/vinyldns-java/pull/84'**

**Comment by pauljamescleary** [comment]
Thanks @djordan17 !
